### ISSUE TITLE
Make pkg-config path generation support cross compiling

### ISSUE THREAD

**Issue by lu-zero** [lu-zero/cargo-c#210]
The paths are built using the os-specific `std::path::Path`, make pkg-config aware of the target and rewrite the paths using the correct separator for the target.

**Comment by 1480c1** [comment]
Compiling ffmpeg with mingw-w64-x86_64-clang from msys2 fails when compiling the rav1e libavcodec/librav1e.o due to not finding rav1e.h, mingw-w64-x86_64-gcc is fine.

The failure seems to stem from `-I${includedir}\rav1e` as changing that to `-I${includedir}/rav1e` makes the compilation successful. Unsure if the issue is that clang is somehow interpreting the `\r` as a carriage return or somewhere else.
