### ISSUE TITLE
Header Regeneration is Wonky on Rebuild

### ISSUE THREAD

**Issue by dwbuiten** [lu-zero/cargo-c#22]
Right now, header generation generates some weird broken header (with wrong types, for example), or doesn't regnerate the header(s) at all, even though the C library is rebuilt.

Example:
1. `git clone https://github.com/xiph/rav1e/`
2. `cd rav1e && cargo cinstall --prefix=whatever`
3. `vim src/capi.rs` and add a function or something
4. `cargo cinstall --prefix=/whatever`
5. Header is wrong.

If I run, e.g. `git clean -fdx` an then re-run `cinstall`, the header is generated correctly.

**Comment by lu-zero** [comment]
It is a subset of #21. as workaround you can remove the buildinfo file for now.

**Comment by dwbuiten** [comment]
Ah, OK, I was not sure, but #21 reminded me when I saw it. Closing then.

**Comment by lu-zero** [comment]
We'd need to investigate why this happens though since in theory changing a file should trigger a rebuild in cargo and the rebuild should provide a different build info. If you could act as second brain [here](https://github.com/lu-zero/cargo-c/blob/master/src/main.rs#L472) is where the bug could possibly be.
