### ISSUE TITLE
Custom CFLAGS/LDFLAGS? 

### ISSUE THREAD

**Issue by cpu** [lu-zero/cargo-c#351]
I might be overlooking an easy solution, but is there a way to specify additional `CFLAGS`/`LDFLAGS` to get passed through to the `cc` crate for building the native code?

I'm interested in conditionally building with ASAN when using `clang`. In a `Makefile` I would write:
```
	CFLAGS += -fsanitize=address -fsanitize=undefined
	LDFLAGS += -fsanitize=address
```

**Comment by lu-zero** [comment]
For the rust code, the [sanitizer](https://doc.rust-lang.org/beta/unstable-book/compiler-flags/sanitizer.html) unstable flag is what you want.

Keep in mind that because how `cargo --target` works (that's what is being used under the hood by cargo-c) you have would have to pass them as `{TARGET}_RUSTFLAGS` or use `RUSTC_WRAPPER`.

If you have some code that has to be built by `cc-rs`, You may set `{TARGET}_CFLAGS` and `{TARGET}_LDFLAGS`.

If you point me to the code I can look into.

**Comment by cpu** [comment]
Those are helpful pointers, thank you! I think my overall goal was confused and I need to revisit. Sorry for the noise :-)

**Comment by lu-zero** [comment]
No problem, feel free to reach me on irc or zulip (or telegram) in case.
