### ISSUE TITLE
cargo-c 0.10.4 is not buildable on Rust 1.78 & 1.79

### ISSUE THREAD

**Issue by AJIOB** [lu-zero/cargo-c#407]
orion-rs published their version 0.17.7 with MSRV 1.80 & it breaks clean builds.

Please, provide the Cargo.lock file for building on MSRV of your project (aka 1.78).

P.S. Looks like lots of previous releases cannot be built too

**Comment by lu-zero** [comment]
if you use cargo install --locked it does not work?

**Comment by AJIOB** [comment]
This project indirectly depends on orion-rs.
As you know, Rust builds all the dependencies locally.

I've tested in the clear local docker environment, it's not a GitHub bug.

For calling `cargo install --locked` your repository must provide `Cargo.lock` file. For now, it doesn't do it. And I suggestes you to do it.

Please, try to call `cargo install cargo-c` inside the clear `rust:1.78` docker/podman image. You will see that's I'm talking about.

**Comment by lu-zero** [comment]
Ok, now I see the problems

**Comment by lu-zero** [comment]
there are 2 issues:
- I did not bump the msrv to match cargo (my fault), I'll publish this weekend a version with it fixed.
- orion-rs bumped their mrsv, but since I did not bump the msrv using --locked you still see problems

In general I suggest to use the cargo-c matching the cargo version in use, so
```
cargo +1.78 install cargo-c@0.10.2 --locked
```
Does solve your problem.

**Comment by AJIOB** [comment]
Closed, becase we resolved it with private fork & Cargo.lock file
