### ISSUE TITLE
RFE: make intermediate output directory predictable

### ISSUE THREAD

**Issue by ensc** [lu-zero/cargo-c#418]
atm, cargo-c seams to place its files below `$CARGO_TARGET_DIR/$ARCH`. $ARCH depends on cargo options and afais, its value is not exported by `cargo metadata`.

This makes it very difficulty to use intermediate files (e.g. the -uninstalled.pc) because their location is difficulty to calculate.

It forces also rebuilds between `cargo build` and `cargo cbuild` because their output directories differ.

Would it be possible to use the normal output directory (which can be derived from `cargo metadata` -> `target_directory`)?

**Comment by lu-zero** [comment]
Sadly is not possible, since having the target architecture set explicitly workarounds cargo not having other mean to separate between host/build-script and target flags yet.

It's location is printed if you pass `-v`, but it is predictable assuming you know your target architecture.

What is forcing rebuilds between `cargo build` and `cargo cbuild` is the mere fact the compiler line is different and there is no way out of this.

Once cargo gets better ways to set the per-target flags probably the default target can be shared, but would anyway cause rebuilds :/
